version: "3.9"
services:
  db:
    container_name: db
    image: postgres:14.15
    environment:
      - POSTGRES_USER=symfony_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=symfony_app
    volumes:
      - dbdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U symfony_user -d symfony_app'"]
      interval: 5s
      timeout: 3s
      retries: 3

  php:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:db"

volumes:
  dbdata:
